version: '2'
services:
    db:
        image: postgres
        volumes:
            - ./pgdata:/pgdata
        environment:
            POSTGRES_DB: src_development
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password4postgres
            PGDATA: /pgdata
    redis:
        image: redis
    web:
        build: .
        command: bundle exec rails server --port 3000 --binding 0.0.0.0
        volumes_from:
            - container:src-web-sync:rw
            - container:src-bundle-sync:rw
        volumes:
            - ./keys:/root/.ssh/
        ports:
            - "3000:3000"
        environment:
            REDIS_URL: redis://redis:6379
        links:
            - db
            - redis
    job:
        build: .
        command: bundle exec sidekiq
        volumes_from:
            - container:src-web-sync:rw
            - container:src-bundle-sync:rw
        volumes:
            - ./keys:/root/.ssh/
        ports:
            - "6379:6379"
        environment:
            REDIS_URL: redis://redis:6379
        links:
            - db
            - redis
volumes:
    src-web-sync:
        external: true
    src-bundle-sync:
        external: true
